### ISSUE TITLE
Node.js Lambda 関数をコンテナイメージとともにデプロイする

### ISSUE THREAD

**Issue by tknry1216** [Takenari-Yamamoto/lambda-practice#1]
これやってみるだけ
https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/nodejs-image.html

**Comment by tknry1216** [comment]
こんな感じ作成
```
.
|-- README.md
|-- app
`-- infra
```

**Comment by tknry1216** [comment]
app直下で
```
npm init -y
```

構成はこんな感じ
```bash
|-- app
|   |-- Dockerfile
|   |-- package-lock.json
|   |-- package.json
|   `-- src
|       `-- index.js

```

**Comment by tknry1216** [comment]
index.js
```javascript
export async function handler() {
  const response = {
    body: JSON.stringify("Hello Take!!"),
    statusCode: 200,
  };
  return response;
}
```

**Comment by tknry1216** [comment]
Dockerfile
```Dockerfile
# REF: https://github.com/aws/aws-lambda-base-images/blob/nodejs20.x/Dockerfile.nodejs20.x
FROM public.ecr.aws/lambda/nodejs:20

COPY src/index.js ${LAMBDA_TASK_ROOT}

CMD [ "index.handler" ]
```

ほとんどチュートリアル通りだが、index.jsのパスだけsrc直下にあるため修正

一応解説

```dockerfile
FROM public.ecr.aws/lambda/nodejs:20
```
- AWSが提供するNode.js 20のLambda対応イメージを使用


```dockerfile
COPY src/index.js ${LAMBDA_TASK_ROOT}
```
- LAMBDA_TASK_ROOTとはAWS Lambda 環境での環境変数の1つ。
- Lambda 関数のコードが配置されるディレクトリのパスが格納される、らしい
- 今回は Lambda関数はsrc/index.js にあるのでそちらを指定

```Dockerfile
CMD [ "index.handler" ]
```

- LAMBDA_TASK_ROOTの内のファイルを実行する
- lambdaのハンドラーは`ファイル名/ハンドラーの関数の名前`にあるので、`index.handler`になる
- なのでファイル名を`app.js`にし、ハンドラーを`main`にすると`app.main`というハンドラー名にすることも可能

**Comment by tknry1216** [comment]
ビルドしてみる
appディレクトリ直下に移動して

```bash
docker build -t ${イメージの名前} .
```

ビルドが完了したらRUNしてみる

```bash
docker run --rm -p 9000:8080 ${イメージの名前}
```

curlで動作確認
```bash
curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
```

エラー
```bash
{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token 'export'","trace":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token 'export'","    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)","    at async start (file:///var/runtime/index.mjs:1282:23)","    at async file:///var/runtime/index.mjs:1288:1"]}%         
```

**Comment by tknry1216** [comment]
index.jsの書き方がejsになってたからダメっぽい
[デフォルトだとCommonJsになる](https://gmo-aozora.hatenablog.com/entry/2023/02/17/110732#:~:text=%E3%82%92%E3%81%97%E3%81%AA%E3%81%84%E9%99%90%E3%82%8A%E3%80%81-,%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%81%A7CommonJS,-%E3%81%A8%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82)みたいなので今回はcommonjsで書き換えとく

```javascript
exports.handler = async () => {
  const response = {
    body: JSON.stringify("Hello Take"),
    statusCode: 200,
  };
  return response;
};

```

これもあとで読んでみよっと

https://zenn.dev/yodaka/articles/596f441acf1cf3#es-modules%E3%81%AB%E5%85%A8%E6%8C%AF%E3%82%8A%E3%81%99%E3%82%8B%E4%B8%8A%E3%81%A7%E3%81%AE%E5%95%8F%E9%A1%8C%E7%82%B9

**Comment by tknry1216** [comment]
再度ビルドしてRUNする
```bash
docker build -t ${イメージの名前} .
docker run --rm -p 9000:8080 ${イメージの名前}
```
そしてcurl叩く
```
curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
```

いけてそう

```bash
curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
{"body":"\"Hello Take\"","statusCode":200}%  
```

**Comment by tknry1216** [comment]
作成したイメージをECRにプッシュ、、する前にterraformで設定しておく

**Comment by tknry1216** [comment]
インフラ側作業内容

- infraディレクトリ移動
- main.tf作成
- terraform init
- .gitignore作成
- イメージ保存のecr作る
- terraform apply

**Comment by tknry1216** [comment]
ECRができたのでさっきビルドしたイメージをPUSHする

ECRにログイン
これをやることで後続のプッシュコマンドに認証情報を渡すことができる
```bash
aws ecr get-login-password --region <リージョン名> | docker login --username AWS --password-stdin <AWSアカウントID>.dkr.ecr.<リージョン名>.amazonaws.com
```

タグ付け

```bash
docker tag ${イメージ名}:latest ${リポジトリURI}/${ECRのリポジトリの名前}:latest
```

ちなみに「リポジトリURI」は下記で確認可能

```bash
aws ecr describe-repositories --region ${リージョン名}
```

プッシュする

```bash
docker push [AWSアカウントID].dkr.ecr.[リージョン].amazonaws.com/[リポジトリ名]:[タグ]
```

**Comment by tknry1216** [comment]
コンソールにイメージがあることを確認

**Comment by tknry1216** [comment]
続いてインフラで下記設定
- lambda 操作用のIAM作成
- ポリシーのアタッチ
- lambda 関数作成
- apply

**Comment by tknry1216** [comment]
これでいけるはずと思いきやエラー
<img width="1388" alt="スクリーンショット 2024-04-17 13 51 37" src="https://github.com/Takenari-Yamamoto/lambda-practice/assets/64131315/1501bd96-7508-49f4-8c38-ef189efbbbe8">

**Comment by tknry1216** [comment]
これで試してみる

https://stackoverflow.com/questions/77802112/using-aws-lambda-docker-error-lambda-entrypoint-sh-exec-format-error


```bash
docker build -t  ${イメージ名} --platform linux/x86_64 .
```

**Comment by tknry1216** [comment]
RUN
```bash
 docker run --rm -p 9000:8080 ${イメージ名}
```
```bash
 curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
{"body":"\"Hello Take\"","statusCode":200}%
```
動くことも確認

**Comment by tknry1216** [comment]
タグ付け、ログイン、PUSHを実行
```bash
// タグ付け
docker tag ${イメージ名}:latest ${リポジトリURI}/${ECRのリポジトリの名前}:latest

// ログイン
aws ecr get-login-password --region <リージョン名> | docker login --username AWS --password-stdin <AWSアカウントID>.dkr.ecr.<リージョン名>.amazonaws.com


// プッシュ
docker push [AWSアカウントID].dkr.ecr.[リージョン].amazonaws.com/[リポジトリ名]:[タグ]

```

**Comment by tknry1216** [comment]
lambda自体も更新する必要がある。
これで対応可能

```bash
aws lambda update-function-code --function-name [関数名] --image-uri [新しいイメージのURI]
```

基本的にはイメージのURIは変わらないはず

**Comment by tknry1216** [comment]
いけたー

<img width="1140" alt="スクリーンショット 2024-04-17 14 08 21" src="https://github.com/Takenari-Yamamoto/lambda-practice/assets/64131315/3056d34b-05f3-4fd3-98bb-c294d4f985b3">

**Comment by tknry1216** [comment]
アプリケーションコードを修正→lambda関数にも反映させる時はこんな感じの流れでいけそう

```bash
# Dockerイメージをビルドする
docker build -t ${イメージ名} --platform linux/x86_64 .

# ログイン
aws ecr get-login-password --region <リージョン名> | docker login --username AWS --password-stdin <AWSアカウントID>.dkr.ecr.<リージョン名>.amazonaws.com

# タグを付ける
docker tag ${イメージ名}:latest ${リポジトリURI}/${ECRのリポジトリの名前}:latest

# ECRにプッシュする
docker push [AWSアカウントID].dkr.ecr.[リージョン].amazonaws.com/[リポジトリ名]:[タグ]

# lambdaにデプロイする
aws lambda update-function-code --function-name [関数名] --image-uri [イメージのURI]

```

**Comment by tknry1216** [comment]
原因
- M2 Mac上ではDockerイメージのビルドのデフォルトがArm64になっており、Lambda上でのDockerイメージのアーキテクチャ（x86_64）と異なっている


解決策
- そのため下記のどちらかで修正できるはず
  - docker ビルド時に --platform linux/x86_64を指定する
  - lambdaのアーキテクチャを arm64 に変更
